name: JS CHECK

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint
